"""Fixed user refresh_token

Revision ID: 8fc058ab89ca
Revises: b3d532f069e4
Create Date: 2024-11-29 22:21:14.510081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fc058ab89ca'
down_revision: Union[str, None] = 'b3d532f069e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
