"""Add username and password_hash to users

Revision ID: 94109d0b5939
Revises: 49d63a0d8eb7
Create Date: 2024-11-29 19:24:56.363123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94109d0b5939'
down_revision: Union[str, None] = '49d63a0d8eb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
